version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 5

  servicedb:
    build: servicedb
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    depends_on:
      rabbitmq:
        condition: service_healthy

  frontend:
    build: frontend
    ports:
      - "80:80"

  backend:
    build: backend
    container_name: 'backend'
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      rabbitmq:
        condition: service_healthy
